services:
  backend:
    build:
      context: ./app/
    image: ntg
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - env.vars
    networks:
      - net

networks:
  net:
    external: false
