services:
  backend:
    build:
      context: app/
    image: ntg
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - env.vars
    networks:
      - net

  database:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - env.vars
    networks:
      - net
    volumes:
      - ntg_database:/var/lib/postgresql/data

networks:
  net:
    external: false

volumes:
  ntg_database:
