// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func StatsSection() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"section stats-section\"><div class=\"container\"><div class=\"section-title animate-on-scroll\"><h2 style=\"color: white;\">Статистика</h2><p style=\"color: rgba(255, 255, 255, 0.8);\">НТГ в цифри</p></div><div class=\"row g-4\"><div class=\"col-md-3\"><div class=\"stat-card animate-on-scroll\"><div class=\"stat-number\">1350</div><h4>Ученици</h4><p>Обучение на високо ниво</p></div></div><div class=\"col-md-3\"><div class=\"stat-card animate-on-scroll delay-1\"><div class=\"stat-number\">95</div><h4>Учители</h4><p>Висококвалифицирани специалисти</p></div></div><div class=\"col-md-3\"><div class=\"stat-card animate-on-scroll delay-2\"><div class=\"stat-number\">42</div><h4>Класни стаи</h4><p>Модерно оборудване</p></div></div><div class=\"col-md-3\"><div class=\"stat-card animate-on-scroll delay-3\"><div class=\"stat-number\">115</div><h4>Години история</h4><p>Традиция и иновации</p></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
