// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"footer\"><div class=\"container\"><div class=\"row g-5\"><div class=\"col-lg-4\"><h4 class=\"footer-title\">НТГ - Национална Търговска Гимназия</h4><p>Създаваме бъдещите лидери в икономиката и бизнеса чрез иновативно образование и практическа подготовка.</p><div class=\"social-links mt-4\"><a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a> <a href=\"#\"><i class=\"fab fa-twitter\"></i></a> <a href=\"#\"><i class=\"fab fa-instagram\"></i></a> <a href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a> <a href=\"#\"><i class=\"fab fa-youtube\"></i></a></div></div><div class=\"col-lg-4\"><h4 class=\"footer-title\">Бързи връзки</h4><div class=\"row\"><div class=\"col-6\"><div class=\"footer-links\"><a href=\"#\">Начало</a> <a href=\"#\">За нас</a> <a href=\"#\">Документи</a> <a href=\"#\">Прием</a> <a href=\"#\">Програми</a></div></div><div class=\"col-6\"><div class=\"footer-links\"><a href=\"#\">Училищен живот</a> <a href=\"#\">Партньори</a> <a href=\"#\">Новини</a> <a href=\"#\">Контакти</a> <a href=\"#\">Карта на сайта</a></div></div></div></div><div class=\"col-lg-4\"><h4 class=\"footer-title\">Контакти</h4><div class=\"contact-info\"><i class=\"fas fa-map-marker-alt\"></i><div><p>бул. Руски №50, Пловдив 4000</p></div></div><div class=\"contact-info\"><i class=\"fas fa-phone-alt\"></i><div><p>+359 2 987 6543</p></div></div><div class=\"contact-info\"><i class=\"fas fa-envelope\"></i><div><p>info@ntg-school.bg</p></div></div><div class=\"contact-info\"><i class=\"fas fa-clock\"></i><div><p>Понеделник-Петък: 8:00 - 17:00</p></div></div></div></div><div class=\"copyright\"><p>&copy; 2025 НАЦИОНАЛНА ТЪРГОВСКА ГИМНАЗИЯ. Всички права запазени.</p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
