// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func QuickLinks() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"quick-links\"><div class=\"container h-100\"><div class=\"row h-100 g-0\"><div class=\"col-md-3 h-100\"><div class=\"quick-link h-100 animate-on-scroll\"><i class=\"fas fa-project-diagram\"></i><h4>Проекти</h4><p>Нашите иновативни образователни проекти</p></div></div><div class=\"col-md-3 h-100\"><div class=\"quick-link h-100 animate-on-scroll delay-1\"><i class=\"fas fa-school\"></i><h4>Училищен живот</h4><p>Запознайте се с ежедневието в НТГ</p></div></div><div class=\"col-md-3 h-100\"><div class=\"quick-link h-100 animate-on-scroll delay-2\"><i class=\"fas fa-newspaper\"></i><h4>Новини</h4><p>Актуална информация и събития</p></div></div><div class=\"col-md-3 h-100\"><a href=\"#\" class=\"text-decoration-none h-100\"><div class=\"quick-link h-100 animate-on-scroll delay-3\"><i class=\"fas fa-images\"></i><h4>Галерия</h4><p>Снимки от живота в училището</p></div></a></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
